### ISSUE TITLE
Invoking unexpected method, due to dependency conflicts on log4j:log4j.jar

### ISSUE THREAD

**Issue by HelloCoCooo** [ShifuML/guagua#103]
Hi, there are multiple versions of **log4j:log4j:jar** in **guagua-guagua-0.7.8**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **log4j:log4j:jar:1.2.15** can be loaded, and **log4j:log4j:jar:1.2.17** will be shadowed.

As **log4j:log4j:jar:1.2.17** is missing during the build process, method **ml.shifu.guagua.worker.AbstractCombineWorkerComputable: void <clinit>()** actually references method **<org.apache.log4j.net.SMTPAppender: void sendBuffer()>** in the unexpected version **log4j:log4j:jar:1.2.15** via the following invocation path:

`<ml.shifu.guagua.worker.AbstractCombineWorkerComputable: void <clinit>()> 
<org.slf4j.LoggerFactory: org.slf4j.Logger getLogger(java.lang.Class)> 
<org.slf4j.LoggerFactory: org.slf4j.Logger getLogger(java.lang.String)> 
<org.slf4j.impl.Log4jLoggerFactory: org.slf4j.Logger getLogger(java.lang.String)> 
<org.apache.log4j.LogManager: void <clinit>()> 
<org.apache.log4j.helpers.OptionConverter: void selectAndConfigure(java.net.URL,java.lang.String,org.apache.log4j.spi.LoggerRepository)> 
<org.apache.log4j.PropertyConfigurator: void doConfigure(java.net.URL,org.apache.log4j.spi.LoggerRepository)> 
<org.apache.log4j.PropertyConfigurator: void doConfigure(java.util.Properties,org.apache.log4j.spi.LoggerRepository)> <org.apache.log4j.Hierarchy: void resetConfiguration()>
<org.apache.log4j.Hierarchy: void shutdown()>
<org.apache.log4j.Category: void closeNestedAppenders()> 
<org.apache.log4j.net.SMTPAppender: void close()> 
<org.apache.log4j.net.SMTPAppender: void sendBuffer()>
`

By further analyzing, the expected callee **org.apache.log4j.net.SMTPAppender: void sendBuffer()** in shadowed version **log4j:log4j:jar:1.2.17**, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version **log4j:log4j:jar:1.2.15**, which leads to different behaviors.

**Solution:**
Use the newer version log4j:log4j:jar:1.2.17 to keep the version consistency.

**Dependency tree**---
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ guagua-core ---
[INFO] ml.shifu:guagua-core:jar:0.7.8
[INFO] +- org.apache.zookeeper:zookeeper:jar:3.4.5:compile
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.6.1:compile - omitted for conflict with 1.7.5)
[INFO] |  +- (org.slf4j:slf4j-log4j12:jar:1.6.1:compile - omitted for conflict with 1.7.5)
[INFO] |  +- **log4j:log4j:jar:1.2.15:compile**
[INFO] |  |  \- javax.mail:mail:jar:1.4:compile
[INFO] |  |     \- javax.activation:activation:jar:1.1:compile
[INFO] |  \- jline:jline:jar:0.9.94:compile
[INFO] |     \- (junit:junit:jar:3.8.1:compile - omitted for conflict with 4.8)
[INFO] +- org.apache.commons:commons-compress:jar:1.5:compile
[INFO] |  \- org.tukaani:xz:jar:1.2:compile
[INFO] +- io.netty:netty:jar:3.6.2.Final:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.5:compile - omitted for conflict with 1.6.1)
[INFO] |  \- **(log4j:log4j:jar:1.2.17:compile - omitted for conflict with 1.2.15)**
[INFO] +- org.slf4j:slf4j-api:jar:1.7.5:compile
[INFO] \- junit:junit:jar:4.8:test (scope not updated to compile)

Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Similarly, method **ml.shifu.guagua.worker.AbstractCombineWorkerComputable: void <clinit>()** actually references method **org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep()** in the unexpected version log4j:log4j:jar:1.2.15 via the following invocation path:

`<ml.shifu.guagua.worker.AbstractCombineWorkerComputable: void <clinit>()> 
<org.slf4j.LoggerFactory: org.slf4j.Logger getLogger(java.lang.Class)> 
<org.slf4j.LoggerFactory: org.slf4j.Logger getLogger(java.lang.String)> 
<org.slf4j.impl.Log4jLoggerFactory: org.slf4j.Logger getLogger(java.lang.String)> <org.apache.log4j.LogManager: void <clinit>()> 
<org.apache.log4j.helpers.OptionConverter: void selectAndConfigure(java.net.URL,java.lang.String,org.apache.log4j.spi.LoggerRepository)> 
<org.apache.log4j.PropertyConfigurator: void doConfigure(java.net.URL,org.apache.log4j.spi.LoggerRepository)> 
<org.apache.log4j.PropertyConfigurator: void doConfigure(java.util.Properties,org.apache.log4j.spi.LoggerRepository)> 
<org.apache.log4j.Hierarchy: void resetConfiguration()> 
<org.apache.log4j.Hierarchy: void shutdown()> 
<org.apache.log4j.Category: void closeNestedAppenders()> 
<org.apache.log4j.net.SMTPAppender: void close()> 
<org.apache.log4j.net.SMTPAppender: void sendBuffer()> 
<org.apache.log4j.net.SMTPAppender: java.lang.String formatBody()> 
<org.apache.log4j.spi.LoggingEvent: java.lang.String[] getThrowableStrRep()> 
<org.apache.log4j.spi.ThrowableInformation: java.lang.String[] getThrowableStrRep()>
`

By further analyzing, the expected callee **org.apache.log4j.spi.ThrowableInformation: java.lang.String[] getThrowableStrRep()** in shadowed version log4j:log4j:jar:1.2.17, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version log4j:log4j:jar:1.2.15.

Code snippet of **org.apache.log4j.spi.ThrowableInformation: java.lang.String[] getThrowableStrRep()** in log4j:log4j:jar:1.2.15:
![fig1](https://github.com/HelloCoCooo/Test/blob/master/getThrowableStrRep1.2.15.png)

Code snippet of **org.apache.log4j.spi.ThrowableInformation: java.lang.String[] getThrowableStrRep()** in log4j:log4j:jar:1.2.17:
![fig1](https://github.com/HelloCoCooo/Test/blob/master/getThrowableStrRep1.2.17.png)


Method **org.apache.log4j.spi.ThrowableInformation: java.lang.String[] getThrowableStrRep()** included in log4j:log4j:jar:1.2.15 and log4j:log4j:jar:1.2.17 have the same return value. But they have different control flows, and this method in the expected version log4j:log4j:jar:1.2.17 deals with more variables, which leads to different behaviors.

**Comment by HelloCoCooo** [comment]
@pengshanzhang hi, could you help me deal with it? Or may pull a request to solve it?

**Comment by zhangpengshan** [comment]
@HelloCoCooo Thanks a lot for your reporting such issue. Such conflict has been fixed in this PR: https://github.com/ShifuML/guagua/commit/476765882654704f0bdbcab24f2d0d83921179b9 

Now the fix is only in develop branch and you can build new version by yourself if needed.

One question: Could you share how you leverage Guagua?

Thanks,
Zhang David
